<?xml version="1.0"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method = "text" encoding="utf-8"/>	

	<xsl:param name="feed_url"/>
	<xsl:param name="feed_url_escaped"/>
	<xsl:param name="version"/>

<!--
#
#   SingleSub v0.1.1
#   Written by Yakov Shafranovich
#
#   A Project of SolidMatrix Research
#   Website: http://singlesub.sourceforge.net
#   Email:  research@solidmatrix.com
#   
#   Copyright (C) 2005 SolidMatrix Technologies, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
-->

<xsl:template match="/">
/*
Generated by <xsl:value-of select="$version"/>.
SingleSub itself (not the output) is copyright (C) 2005 SolidMatrix Technologies, Inc.
SingleSub itself (not the output) is licensed under the Apache License, Version 2.0.
*/
<xsl:apply-templates select="//outline[@type='subscribe' and @iconUrl]">
 	<xsl:sort select="@text"/>
</xsl:apply-templates>
</xsl:template>

<xsl:template match="outline[@type='subscribe']">
<xsl:choose>
<xsl:when test="@escaped = 'true'">document.writeln('&lt;div class="single_sub_chicklet"&gt;&lt;a href="<xsl:value-of
				   select="concat(@subscribeUrl, $feed_url_escaped)"/>"&gt;&lt;img src="<xsl:value-of
				   select="@iconUrl"/>" alt="Subscribe via <xsl:value-of
				   select="@text"/>" align="middle"/&gt;&lt;/a&gt;&lt;div&gt;');		
</xsl:when>
<xsl:otherwise>document.writeln('&lt;div class="single_sub_chicklet"&gt;&lt;a href="<xsl:value-of
				   select="concat(@subscribeUrl, $feed_url)"/>"&gt;&lt;img src="<xsl:value-of
				   select="@iconUrl"/>" alt="Subscribe via <xsl:value-of
				   select="@text"/>" align="middle"/&gt;&lt;/a&gt;&lt;div&gt;');		
</xsl:otherwise>
</xsl:choose>		
</xsl:template>

<xsl:template match="text()">
</xsl:template>	
	
</xsl:stylesheet>