<?xml version="1.0"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method = "html"	encoding="utf-8"
  	doctype-system="http://www.w3.org/TR/html4/loose.dtd" 
  	doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN"
  	indent="yes"/>
  	
	<xsl:param name="feed_url"/>
	<xsl:param name="feed_url_escaped"/>  	

<!--
#
#   SingleSub v0.1.1
#   Written by Yakov Shafranovich
#
#   A Project of SolidMatrix Research
#   Website: http://singlesub.sourceforge.net
#   Email:  research@solidmatrix.com
#   
#   Copyright (C) 2005 SolidMatrix Technologies, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
-->

	<xsl:template match="/">
 		<html>
 			<head>
 				<title>SingleSub v0.1 HTML Subscribe Page</title>
 				<script src="includes/listCollapse.js" type="text/javascript" language="javascript1.2"></script> 				
				<xsl:comment>
					Generated by SingleSub v0.1.1 (http://singlesub.sf.net). 
					SingleSub itself (not the output) is copyright (C) 2005 SolidMatrix Technologies, Inc.
					SingleSub itself (not the output) is licensed under the Apache License, Version 2.0.
				</xsl:comment> 			
 			</head>
 			<body onLoad="compactMenu('list',true,'&amp;plusmn; ');">
 				<hr/>
				<h1 align="left">SingleSub HTML Subscribe Page</h1>
				<h3 align="left">Feed Location: <I><xsl:value-of select="$feed_url"/></I></h3>
				<hr/>
 				Please choose from one of the aggregators or services below to subscribe to this feed:
 				<ul id="list">
 		 			<xsl:apply-templates/> 
 		 		</ul> 		 		
 		 		<hr/>
 		 		<p align="center">Generated by <xsl:value-of select="$version"/>. Copyright (C) 2005 SolidMatrix Technologies, Inc.
 		 		Please see <a href="http://singlesub.sf.net">http://singlesub.sf.net</a> for more information.
 		 		<br/>
 		 		Collapsible list script provided for free by <a href="http://www.howtocreate.co.u">http://www.howtocreate.co.uk</a>.
 		 		</p>
 		 		<p align="center">
    				<a href="http://validator.w3.org/check?uri=referer">
    					<img
        				src="http://www.w3.org/Icons/valid-html401"
        				alt="Valid HTML 4.01 Transitional" height="31" width="88"/>
        			</a>
  				</p>
  				<hr/>	 	
			</body>
		</html>
	</xsl:template>

	<xsl:template match="outline">
		<xsl:choose>
			<xsl:when test="@type = 'subscribe'">
				<xsl:choose>
				<xsl:when test="@escaped = 'true'">				
					<li><a href="{concat(@subscribeUrl, $feed_url_escaped)}"><xsl:value-of
							 select="@text"/><xsl:if test="@iconUrl"> <img src="{@iconUrl}" alt="icon" align="middle"/></xsl:if></a></li>
				</xsl:when>
				<xsl:otherwise>
					<li><a href="{concat(@subscribeUrl, $feed_url)}"><xsl:value-of
							 select="@text"/><xsl:if test="@iconUrl"> <img src="{@iconUrl}" alt="icon" align="middle"/></xsl:if></a></li>
				</xsl:otherwise>
				</xsl:choose>
			</xsl:when>
			<xsl:otherwise>
				<li><xsl:value-of select="@text"/>
					<ul>
						<xsl:apply-templates/>
					</ul>
				</li>
			</xsl:otherwise>			
		</xsl:choose>
	</xsl:template>

	<xsl:template match="text()">
	</xsl:template>	
	
</xsl:stylesheet>